version: '3.6'

services:
  # !! WARNING: !!
  # If using linuxserver/mariadb, you will need to add
  # skip-log-bin to mysqld and disable all log_bin options
  db:
    image: mariadb
    restart: always
    networks:
      - zoneminder
    volumes:
      - ./zm/db:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_DATABASE=zm
      - TZ=America/Sao_Paulo

    env_file:
      - ./.env
    ports:
    - "3307:3306"

  zoneminder:
    image: ghcr.io/zoneminder-containers/zoneminder-base:latest
    restart: always
    stop_grace_period: 45s
    depends_on:
      - db
    ports:
      - 80:80
    networks:
      - zoneminder
    volumes:
      - ./zm/data:/data
      - ./zm/config:/config
      - ./zm/log:/log
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 1000000000
      - /dev/video0:/dev/video0
    env_file:
      - ./.env
    environment:
      - TZ=America/Sao_Paulo
    privileged: true
#    environment:
#      - ZM_SERVER_HOST=zoneminder1



networks:
  zoneminder:
